name:                nuuanu
version:             0.1.0.0
github:              "Kapranov/nuuanu"
license:             BSD-3-Clause
author:              "Oleg G.Kapranov"
maintainer:          "lugatex@yahoo.com"
copyright:           "Copyright (c) 2024 Oleg G.Kapranov"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/Kapranov/nuuanu#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: [benchmarks, src]
  dependencies:
    - aeson
    - base16
    - base64-bytestring
    - bytestring
    - criterion
    - criterion-measurement
    - crypton
    - doctest
    - entropy
    - fakedata
    - jose-jwt
    - jsonifier
    - memory
    - mtl
    - network
    - random
    - scotty
    - text
    - time
    - uuid
    - websockets
    - wuss
    - th-lift-instances
    - containers
    - template-haskell
    - validation-selective
    - protobuf
    - cereal
    - attoparsec
    - parser-combinators
    - megaparsec
    - regex-tdfa
    - async
    - servant-server
    - wai
    - text-display
    - filepath
    - unix

executables:
  nuuanu-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nuuanu
    when:
    - condition: false
      other-modules: Paths_nuuanu

tests:
  nuuanu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nuuanu
    - hspec
    - QuickCheck
    - bytestring
    - tasty
    - tasty-hunit
